### PR TITLE
Fix namespace calling of SVD_FUNS to backend.SVD_FUNS

### PR DESCRIPTION
**Pull request by nobodyzxc**
I run `python examples/decomposition/plot_image_compression.py`:
```
Traceback (most recent call last):
  File "decomposition/plot_image_compression.py", line 43, in <module>
    core, tucker_factors = tucker(image, rank=tucker_rank, init='random', tol=10e-5, random_state=random_state)
  File "~/.local/lib/python3.6/site-packages/tensorly/decomposition/_tucker.py", line 271, in tucker
    verbose=verbose)
  File "~/.local/lib/python3.6/site-packages/tensorly/decomposition/_tucker.py", line 137, in partial_tucker
    svd_fun = tl.SVD_FUNS[svd]
AttributeError: module 'tensorly' has no attribute 'SVD_FUNS'
```
SVD_FUNS were moved the backend, and they should change the way to be called in api functions.
(tensorly.SVD_FUNS to tensorly.backend.SVD_FUNS)

### CODE REVIEW

**Comment by nobodyzxc** [comment]
oh no, there's not only SVD_FUNS, also index, index_update are also should be corrected, I'll make other commits later.

**Comment by nobodyzxc** [comment]
it's version problem on python3.6, works fine on python3.9, closed
