### ISSUE TITLE
Sparse nonnegative parafac decomposition won't run on a COO object?

### ISSUE THREAD

**Issue by dswalter** [tensorly/tensorly#131]
I have a sparse COO array that I'm attempting to decompose in a sparse manner. 
Here is my input array. 

```<COO: shape=(15, 12, 18, 19, 12), dtype=float32, nnz=20, fill_value=0.0>```

<img width="224" alt="image" src="https://user-images.githubusercontent.com/7560282/65079552-7048e980-d96d-11e9-8a85-d815fab355b3.png">

I don't appear to have a "sparse" option for a backend, when choosing backends, by the way. 

When I attempt to perform a (regular!) non-negative parafac decomposition, I get an error: 
  ``` 
     158 
     159     def inner(*args, **kwargs):
-->160         return _get_backend_method(name)(*args, **kwargs)
     161 
     162     # We don't use `functools.wraps` here because some of the dispatched

<__array_function__ internals> in shape(*args, **kwargs)

TypeError: no implementation found for 'numpy.moveaxis' on types that implement __array_function__: [<class 'sparse._coo.core.COO'>]
```

When I instead attempt to use the sparse non-negative parafac decomposition, I get a different error.

```
      158 
      159     def inner(*args, **kwargs):
-->160         return _get_backend_method(name)(*args, **kwargs)
      161 
      162     # We don't use `functools.wraps` here because some of the dispatched

<__array_function__ internals> in shape(*args, **kwargs)

TypeError: no implementation found for 'numpy.shape' on types that implement __array_function__: [<class 'sparse._coo.core.COO'>]
```

Is there something I'm doing wrong in getting my environment set up, or are COO arrays not yet ready for prime time? 

Thanks,
Daniel 

#### Versions

Darwin-17.7.0-x86_64-i386-64bit
Python 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 12:34:36) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.17.2
SciPy 1.3.1
TensorLy 0.4.4

**Comment by dswalter** [comment]
After some further digging, it appears this is related to numpy 1.17 which adds the `__array_function__` protocol. This will eventually lead to some benefits that will probably be great for projects like tensorly, but is currently a minor issue.

**Comment by dswalter** [comment]
For now, downgrading to numpy 1.16 helps.

**Comment by JeanKossaifi** [comment]
Did downgrading "fix" the issue?
@asmeurer or @hameerabbasi would you know if this is perhaps a known issue?

**Comment by dswalter** [comment]
Sorry for not being clear. Downgrading meant I no longer saw the issue, so everything worked. From what I read in the numpy docs, though. This __array__function__ protocol in Numpy is going to be the great new way forward, though, so it will need to be addressed unless tensorly sparse decompositions are going to only work on pre-1.17 numpy.

**Comment by JeanKossaifi** [comment]
Indeed, thanks for reporting! :)
I'll try to see how this can be fixed as soon as I get a moment. Feel free to have a crack at it if you have an idea on how this can be fixed!

**Comment by asmeurer** [comment]
It looks like a bug in sparse if moveaxis doesn't work. It's probably easy to fix here, though. Just change it so that it uses the same custom `moveaxis` as some of the other backends (e.g., tensorflow).

**Comment by JeanKossaifi** [comment]
Thanks @asmeurer 
I pushed a temporary fix in 70142977dfd30dcdbdf90f60d5ed8fcf0ec22dd8.

**Comment by isokiso** [comment]
I faced the similar problem when running Sparse nonnegative parafac decomposition. The function `clip` doesn't work with numpy_backend. 
Here is the error message.
` TypeError: clip() got an unexpected keyword argument 'a_min' `
I fixed the code around line 201 in tensorly/contrib/sparse/backend/numpy_backend.py
from
`for name in ['int64', 'int32', 'float64', 'float32', 'transpose',
             'reshape', 'ndim', 'max', 'min', 'all', 'mean', 'sum',
             'prod', 'sqrt', 'abs', 'sign', 'clip', 'arange', 'conj']:
    NumpySparseBackend.register_method(name, getattr(np, name)) `
to
`for name in ['int64', 'int32', 'float64', 'float32', 'transpose',
             'reshape', 'ndim', 'max', 'min', 'all', 'mean', 'sum',
             'prod', 'sqrt', 'abs', 'sign', 'arange', 'conj']:
    NumpySparseBackend.register_method(name, getattr(np, name)) `
Then it worked.

**versions**
tensorly: 0.4.6
numpy: 1.17.4
sparse: 0.9.1

**Comment by hameerabbasi** [comment]
`np.clip` exists, and it dispatched to `COO.clip`. That function takes `min` and `max` instead of `a_min` and `a_max`.

I can push a small change changing these names. In the meanwhile, a fix would be to use positional arguments instead of keyword arguments.

**Comment by hameerabbasi** [comment]
Reported in pydata/sparse#338 and fixed in pydata/sparse#339. If you pull from `master` it should be fixed.

**Comment by JeanKossaifi** [comment]
Thanks a lot @hameerabbasi !

**Comment by 20zinnm** [comment]
I encountered a similar error trying to use `tensorly.contrib.sparse.kruskal_to_tensor` with the output of `tensorly.contrib.sparse.decomposition.parafac`. Downgrading Numpy to 1.16 did not solve the error. Give me a few minutes and I'll copy over the stack trace.

**Comment by 20zinnm** [comment]
Interesting... Today, I'm no longer getting the error. Instead, the memory usage is exploding like it's creating a dense tensor. I imagine the problem stems from the fact that most of the reconstructed tensor elements are nonzero, even if some are extremely small. Could we add a threshold to `tensorly.contrib.sparse.kruskal_to_tensor` to try and address this issue?

**Comment by JeanKossaifi** [comment]
Hi @20zinnm. 
The original error should be fixed in Master indeed. However, it seems one of the functions is no longer sparse safe and causes the sparse tensor to be made dense, I am trying to track down the issue.

**Comment by JeanKossaifi** [comment]
Should be fixed now.
